<a href="https://colab.research.google.com/github/Devil-99/numpy/blob/main/numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#creating array
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#dimension of the array
print(a.ndim)

#byte size of each elemnet
print(a.itemsize)

#datatype of element
print(a.dtype)

2
8
int64


In [2]:
b=np.array([(1,2,3,4,5,6),(7,8,9,10,11,12),(13,14,15,16,17,18)])
print(b)

#size = no of element
print(b.size)

#shape of array (row,column)
print(b.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
18
(3, 6)


In [ ]:
#Reshaping of array ie. transpose
c=b.reshape(2,9)

print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [ ]:
#slicing an array

#if we want to print 5
print(b[0,4])

#if we want to print the 4th element in both row
print(b[0:,4])
# 0: means all rows from 0 including

#if we want to print 4th element in 1st 2 row
print(b[0:2,4])
# 0:n means rows form 0 to n-1

5
[ 5 11 17]
[ 5 11]


In [ ]:
# linespace

x=np.linspace(1,5,10)
# 10 element from 1 to 3 with equal space in between
print(x)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


## Operation Funtions

In [ ]:
import numpy as np

a=np.array([1,2,3])

#sum
print(a.sum())
#max
print(a.max())
#min
print(a.min())

6
3
1


In [ ]:
b=np.array([(1,2,3),(4,5,6)])

# columns are called axis 0
# Rows are called axis 1

print(b.sum(axis=0))
print(b.sum(axis=1))

[5 7 9]
[ 6 15]


In [ ]:
# square root

print(np.sqrt(a))

# star=nderd daviation
print(np.std(a))

[1.         1.41421356 1.73205081]
0.816496580927726
